/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "audit-policy": () => import("@/views/audit-policy/index.vue"),
  audit: () => import("@/views/audit/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  "feature-flag": () => import("@/views/feature-flag/index.vue"),
  language: () => import("@/views/language/index.vue"),
  permission: () => import("@/views/permission/index.vue"),
  role: () => import("@/views/role/index.vue"),
  tenant: () => import("@/views/tenant/index.vue"),
  "theme-config": () => import("@/views/theme-config/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  user: () => import("@/views/user/index.vue"),
};
