/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'audit',
    path: '/audit',
    component: 'layout.base$view.audit',
    meta: {
      title: 'audit',
      i18nKey: 'route.audit'
    }
  },
  {
    name: 'audit-policy',
    path: '/audit-policy',
    component: 'layout.base$view.audit-policy',
    meta: {
      title: 'audit-policy',
      i18nKey: 'route.audit-policy'
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard'
    }
  },
  {
    name: 'feature-flag',
    path: '/feature-flag',
    component: 'layout.base$view.feature-flag',
    meta: {
      title: 'feature-flag',
      i18nKey: 'route.feature-flag'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'language',
    path: '/language',
    component: 'layout.base$view.language',
    meta: {
      title: 'language',
      i18nKey: 'route.language'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'permission',
    path: '/permission',
    component: 'layout.base$view.permission',
    meta: {
      title: 'permission',
      i18nKey: 'route.permission',
      order: 4
    }
  },
  {
    name: 'role',
    path: '/role',
    component: 'layout.base$view.role',
    meta: {
      title: 'role',
      i18nKey: 'route.role',
      order: 3
    }
  },
  {
    name: 'tenant',
    path: '/tenant',
    component: 'layout.base$view.tenant',
    meta: {
      title: 'tenant',
      i18nKey: 'route.tenant',
      order: 2
    }
  },
  {
    name: 'theme-config',
    path: '/theme-config',
    component: 'layout.base$view.theme-config',
    meta: {
      title: 'theme-config',
      i18nKey: 'route.theme-config'
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: 'user',
      i18nKey: 'route.user'
    }
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
