/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * Generated by `pnpm api:types`.
 *
 * Sources:
 * - ../obsidian-admin-laravel/app/DTOs
 * - ../obsidian-admin-laravel/app
 */
declare namespace BackendGenerated {
  namespace DTO {
    namespace Audit {
      interface ListAuditLogsInputDTO {
        current: number;
        size: number;
        cursor: string | null;
        keyword: string;
        action: string;
        logType: string;
        userName: string;
        requestId: string;
        dateFrom: string;
        dateTo: string;
      }

      interface ListAuditPolicyHistoryInputDTO {
        current: number;
        size: number;
      }

      interface UpdateAuditPoliciesInputDTO {
        records: unknown[];
        changeReason: string;
      }

      interface UpdateAuditPolicyRecordInputDTO {
        action: string;
        enabled: boolean;
        samplingRate: number | null;
        retentionDays: number | null;
      }
    }

    namespace Auth {
      interface ForgotPasswordInputDTO {
        email: string;
      }

      interface LoginInputDTO {
        userName: string | null;
        email: string | null;
        password: string;
        rememberMe: boolean;
        otpCode: string | null;
        locale: string | null;
      }

      interface LogoutInputDTO {
        refreshToken: string | null;
      }

      interface RefreshTokenInputDTO {
        refreshToken: string;
      }

      interface RegisterInputDTO {
        name: string;
        email: string;
        password: string;
      }

      interface ResetPasswordInputDTO {
        token: string;
        email: string;
        password: string;
        passwordConfirmation: string;
      }

      interface RevokeSessionInputDTO {
        sessionId: string;
      }

      interface TwoFactorCodeInputDTO {
        otpCode: string;
      }

      interface UpdatePreferredLocaleInputDTO {
        locale: string;
      }

      interface UpdateProfileInputDTO {
        userName: string;
        email: string;
        currentPassword: string | null;
        password: string | null;
        timezone: string | null;
      }

      interface UpdateSessionAliasInputDTO {
        sessionId: string;
        deviceAlias: string | null;
      }

      interface UpdateUserPreferencesInputDTO {
        hasThemeSchema: boolean;
        themeSchema: string | null;
        hasTimezone: boolean;
        timezone: string | null;
      }
    }

    namespace FeatureFlag {
      interface ForgetFeatureFlagOverrideDTO {
        key: string;
        scope: string;
      }

      interface ListFeatureFlagsDTO {
        current: number;
        size: number;
        keyword: string;
      }

      interface PurgeFeatureFlagDTO {
        key: string;
      }

      interface SetFeatureFlagOverrideDTO {
        key: string;
        scope: string;
        enabled: boolean;
      }

      interface ToggleFeatureFlagDTO {
        key: string;
        enabled: boolean;
      }
    }

    namespace Language {
      interface CreateLanguageTranslationDTO {
        languageId: number;
        translationKey: string;
        translationValue: string;
        description: string;
        status: string;
      }

      interface ListLanguageTranslationsInputDTO {
        current: number;
        size: number;
        cursor: string | null;
        locale: string;
        keyword: string;
        status: string;
      }

      interface StoreLanguageTranslationInputDTO {
        locale: string;
        translationKey: string;
        translationValue: string;
        description: string;
        status: string;
      }

      interface UpdateLanguageTranslationDTO {
        languageId: number;
        translationKey: string;
        translationValue: string;
        description: string;
        status: string;
      }

      interface UpdateLanguageTranslationInputDTO {
        locale: string;
        translationKey: string;
        translationValue: string;
        description: string;
        status: string | null;
      }
    }

    namespace Organization {
      interface CreateOrganizationDTO {
        organizationCode: string;
        organizationName: string;
        description: string;
        status: string;
        sort: number;
      }

      interface ListOrganizationsInputDTO {
        current: number;
        size: number;
        cursor: string | null;
        keyword: string;
        status: string;
      }

      interface UpdateOrganizationDTO {
        organizationCode: string;
        organizationName: string;
        description: string;
        status: string | null;
        sort: number | null;
      }
    }

    namespace Permission {
      interface CreatePermissionDTO {
        code: string;
        name: string;
        group: string;
        description: string;
        status: string;
      }

      interface ListPermissionsInputDTO {
        current: number;
        size: number;
        cursor: string | null;
        keyword: string;
        status: string;
        group: string;
      }

      interface StorePermissionInputDTO {
        permissionCode: string;
        permissionName: string;
        group: string;
        description: string;
        status: string;
      }

      interface UpdatePermissionDTO {
        code: string;
        name: string;
        group: string;
        description: string;
        status: string;
      }

      interface UpdatePermissionInputDTO {
        permissionCode: string;
        permissionName: string;
        group: string;
        description: string;
        status: string | null;
      }
    }

    namespace Role {
      interface CreateRoleDTO {
        code: string;
        name: string;
        description: string;
        status: string;
        tenantId: number | null;
        level: number;
      }

      interface ListRolesInputDTO {
        current: number;
        size: number;
        cursor: string | null;
        keyword: string;
        status: string;
        level: number | null;
      }

      interface StoreRoleInputDTO {
        roleCode: string;
        roleName: string;
        description: string;
        status: string;
        level: number;
        permissionCodes: unknown[];
      }

      interface SyncRolePermissionsDTO {
        permissionIds: unknown[];
      }

      interface SyncRolePermissionsInputDTO {
        permissionCodes: unknown[];
      }

      interface UpdateRoleDTO {
        code: string;
        name: string;
        description: string;
        status: string;
        level: number;
      }

      interface UpdateRoleInputDTO {
        roleCode: string;
        roleName: string;
        description: string;
        status: string | null;
        level: number;
        hasPermissionCodes: boolean;
        permissionCodes: unknown[];
      }
    }

    namespace Team {
      interface CreateTeamDTO {
        organizationId: number;
        teamCode: string;
        teamName: string;
        description: string;
        status: string;
        sort: number;
      }

      interface ListTeamsInputDTO {
        current: number;
        size: number;
        cursor: string | null;
        keyword: string;
        status: string;
        organizationId: number | null;
      }

      interface UpdateTeamDTO {
        organizationId: number;
        teamCode: string;
        teamName: string;
        description: string;
        status: string | null;
        sort: number | null;
      }
    }

    namespace Tenant {
      interface CreateTenantDTO {
        tenantCode: string;
        tenantName: string;
        status: string;
      }

      interface ListTenantsInputDTO {
        current: number;
        size: number;
        cursor: string | null;
        keyword: string;
        status: string;
      }

      interface UpdateTenantDTO {
        tenantCode: string;
        tenantName: string;
        status: string | null;
      }
    }

    namespace Theme {
      interface UpdateThemeConfigInputDTO {
        themeScheme: string | null;
        themeColor: string | null;
        themeRadius: number | null;
        headerHeight: number | null;
        siderWidth: number | null;
        siderCollapsedWidth: number | null;
        layoutMode: string | null;
        scrollMode: string | null;
        darkSider: boolean | null;
        themeSchemaVisible: boolean | null;
        headerFullscreenVisible: boolean | null;
        tabVisible: boolean | null;
        tabFullscreenVisible: boolean | null;
        breadcrumbVisible: boolean | null;
        footerVisible: boolean | null;
        footerHeight: number | null;
        multilingualVisible: boolean | null;
        globalSearchVisible: boolean | null;
        themeConfigVisible: boolean | null;
        pageAnimate: boolean | null;
        pageAnimateMode: string | null;
        fixedHeaderAndTab: boolean | null;
      }
    }

    namespace User {
      interface AssignUserRoleInputDTO {
        roleCode: string;
      }

      interface CreateUserDTO {
        name: string;
        email: string;
        password: string;
        status: string;
        roleId: number;
        tenantId: number | null;
        organizationId: number | null;
        teamId: number | null;
      }

      interface CreateUserInputDTO {
        userName: string;
        email: string;
        roleCode: string;
        organizationId: number | null;
        teamId: number | null;
        status: string;
        password: string;
      }

      interface ListUsersInputDTO {
        current: number;
        size: number;
        cursor: string | null;
        keyword: string;
        userName: string;
        userEmail: string;
        roleCode: string;
        status: string;
      }

      interface UpdateOwnProfileDTO {
        userName: string;
        email: string;
        password: string | null;
        timezone: string | null;
      }

      interface UpdateUserDTO {
        name: string;
        email: string;
        password: string | null;
        status: string;
        roleId: number;
        tenantId: number | null;
        organizationId: number | null;
        teamId: number | null;
      }

      interface UpdateUserInputDTO {
        userName: string;
        email: string;
        roleCode: string;
        organizationId: number | null;
        teamId: number | null;
        status: string | null;
        password: string | null;
      }
    }
  }

  namespace Resource {
    interface AuditLogListResource {
      id: number;
      action: string;
      logType: string;
      userName: unknown;
      tenantId: string;
      tenantName: unknown;
      auditableType: unknown;
      auditableId: string;
      target: string;
      oldValues: unknown;
      newValues: unknown;
      ipAddress: string;
      userAgent: string;
      requestId: string;
      createTime: string;
    }

    interface LanguageTranslationListResource {
      id: number;
      locale: string;
      localeName: string;
      translationKey: string;
      translationValue: string;
      description: string;
      status: string;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface OrganizationListResource {
      id: number;
      tenantId: string;
      tenantName: unknown;
      organizationCode: string;
      organizationName: string;
      description: string;
      status: string;
      sort: number;
      teamCount: number;
      userCount: number;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface PermissionListResource {
      id: number;
      permissionCode: string;
      permissionName: string;
      group: string;
      description: string;
      status: string;
      roleCount: number;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface RoleListResource {
      id: number;
      roleCode: string;
      roleName: string;
      tenantId: string;
      tenantName: unknown;
      description: string;
      status: string;
      level: unknown;
      manageable: unknown;
      userCount: number;
      version: number;
      permissionCodes: string[];
      createTime: string;
      updateTime: string;
    }

    interface TeamListResource {
      id: number;
      tenantId: string;
      organizationId: string;
      organizationName: unknown;
      teamCode: string;
      teamName: string;
      description: string;
      status: string;
      sort: number;
      userCount: number;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface TenantListResource {
      id: number;
      tenantCode: string;
      tenantName: string;
      status: string;
      userCount: number;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface UserListResource {
      id: number;
      userName: string;
      email: string;
      roleCode: unknown;
      roleName: unknown;
      roleLevel: unknown;
      organizationId: string;
      organizationName: unknown;
      teamId: string;
      teamName: unknown;
      status: string;
      manageable: unknown;
      version: number;
      createTime: string;
      updateTime: string;
    }
  }
}
