/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * Generated by `pnpm api:types`.
 *
 * Sources:
 * - ../obsidian-admin-laravel/app/DTOs
 * - ../obsidian-admin-laravel/app
 */
declare namespace BackendGenerated {
  namespace DTO {
    namespace Auth {
      interface LoginInputDTO {
        userName: string | null;
        email: string | null;
        password: string;
        rememberMe: boolean;
        otpCode: string | null;
        locale: string | null;
      }

      interface RefreshTokenInputDTO {
        refreshToken: string;
      }

      interface RegisterInputDTO {
        name: string;
        email: string;
        password: string;
      }

      interface RevokeSessionInputDTO {
        sessionId: string;
      }

      interface UpdateSessionAliasInputDTO {
        sessionId: string;
        deviceAlias: string | null;
      }
    }

    namespace FeatureFlag {
      interface ForgetFeatureFlagOverrideDTO {
        key: string;
        scope: string;
      }

      interface ListFeatureFlagsDTO {
        current: number;
        size: number;
        keyword: string;
      }

      interface PurgeFeatureFlagDTO {
        key: string;
      }

      interface SetFeatureFlagOverrideDTO {
        key: string;
        scope: string;
        enabled: boolean;
      }

      interface ToggleFeatureFlagDTO {
        key: string;
        enabled: boolean;
      }
    }

    namespace Organization {
      interface CreateOrganizationDTO {
        organizationCode: string;
        organizationName: string;
        description: string;
        status: string;
        sort: number;
      }

      interface UpdateOrganizationDTO {
        organizationCode: string;
        organizationName: string;
        description: string;
        status: string | null;
        sort: number | null;
      }
    }

    namespace Team {
      interface CreateTeamDTO {
        organizationId: number;
        teamCode: string;
        teamName: string;
        description: string;
        status: string;
        sort: number;
      }

      interface UpdateTeamDTO {
        organizationId: number;
        teamCode: string;
        teamName: string;
        description: string;
        status: string | null;
        sort: number | null;
      }
    }

    namespace Tenant {
      interface CreateTenantDTO {
        tenantCode: string;
        tenantName: string;
        status: string;
      }

      interface UpdateTenantDTO {
        tenantCode: string;
        tenantName: string;
        status: string | null;
      }
    }

    namespace User {
      interface CreateUserDTO {
        name: string;
        email: string;
        password: string;
        status: string;
        roleId: number;
        tenantId: number | null;
        organizationId: number | null;
        teamId: number | null;
      }

      interface UpdateOwnProfileDTO {
        userName: string;
        email: string;
        password: string | null;
        timezone: string | null;
      }

      interface UpdateUserDTO {
        name: string;
        email: string;
        password: string | null;
        status: string;
        roleId: number;
        tenantId: number | null;
        organizationId: number | null;
        teamId: number | null;
      }
    }
  }

  namespace Resource {
    interface AuditLogListResource {
      id: number;
      action: string;
      logType: string;
      userName: unknown;
      tenantId: string;
      tenantName: unknown;
      auditableType: unknown;
      auditableId: string;
      target: string;
      oldValues: unknown;
      newValues: unknown;
      ipAddress: string;
      userAgent: string;
      requestId: string;
      createTime: string;
    }

    interface LanguageTranslationListResource {
      id: number;
      locale: string;
      localeName: string;
      translationKey: string;
      translationValue: string;
      description: string;
      status: string;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface OrganizationListResource {
      id: number;
      tenantId: string;
      tenantName: unknown;
      organizationCode: string;
      organizationName: string;
      description: string;
      status: string;
      sort: number;
      teamCount: number;
      userCount: number;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface PermissionListResource {
      id: number;
      permissionCode: string;
      permissionName: string;
      group: string;
      description: string;
      status: string;
      roleCount: number;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface RoleListResource {
      id: number;
      roleCode: string;
      roleName: string;
      tenantId: string;
      tenantName: unknown;
      description: string;
      status: string;
      level: unknown;
      manageable: unknown;
      userCount: number;
      version: number;
      permissionCodes: string[];
      createTime: string;
      updateTime: string;
    }

    interface TeamListResource {
      id: number;
      tenantId: string;
      organizationId: string;
      organizationName: unknown;
      teamCode: string;
      teamName: string;
      description: string;
      status: string;
      sort: number;
      userCount: number;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface TenantListResource {
      id: number;
      tenantCode: string;
      tenantName: string;
      status: string;
      userCount: number;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface UserListResource {
      id: number;
      userName: string;
      email: string;
      roleCode: unknown;
      roleName: unknown;
      roleLevel: unknown;
      organizationId: string;
      organizationName: unknown;
      teamId: string;
      teamName: unknown;
      status: string;
      manageable: unknown;
      version: number;
      createTime: string;
      updateTime: string;
    }
  }
}
