/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * Generated by `pnpm api:types`.
 *
 * Sources:
 * - ../obsidian-admin-laravel/app/DTOs
 * - ../obsidian-admin-laravel/app
 */
declare namespace BackendGenerated {
  namespace DTO {
    namespace FeatureFlag {
      interface ForgetFeatureFlagOverrideDTO {
        key: string;
        scope: string;
      }

      interface ListFeatureFlagsDTO {
        current: number;
        size: number;
        keyword: string;
      }

      interface PurgeFeatureFlagDTO {
        key: string;
      }

      interface SetFeatureFlagOverrideDTO {
        key: string;
        scope: string;
        enabled: boolean;
      }

      interface ToggleFeatureFlagDTO {
        key: string;
        enabled: boolean;
      }
    }

    namespace Tenant {
      interface CreateTenantDTO {
        tenantCode: string;
        tenantName: string;
        status: string;
      }

      interface UpdateTenantDTO {
        tenantCode: string;
        tenantName: string;
        status: string | null;
      }
    }

    namespace User {
      interface CreateUserDTO {
        name: string;
        email: string;
        password: string;
        status: string;
        roleId: number;
        tenantId: number | null;
      }

      interface UpdateUserDTO {
        name: string;
        email: string;
        password: string | null;
        status: string;
        roleId: number;
        tenantId: number | null;
      }
    }
  }

  namespace Resource {
    interface AuditLogListResource {
      id: number;
      action: string;
      userName: string;
      tenantId: string;
      tenantName: string;
      auditableType: unknown;
      auditableId: string;
      target: string;
      oldValues: unknown;
      newValues: unknown;
      ipAddress: string;
      userAgent: string;
      requestId: string;
      createTime: string;
    }

    interface LanguageTranslationListResource {
      id: number;
      locale: string;
      localeName: string;
      translationKey: string;
      translationValue: string;
      description: string;
      status: string;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface PermissionListResource {
      id: number;
      permissionCode: string;
      permissionName: string;
      group: string;
      description: string;
      status: string;
      roleCount: number;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface RoleListResource {
      id: number;
      roleCode: string;
      roleName: string;
      tenantId: string;
      tenantName: string;
      description: string;
      status: string;
      level: unknown;
      manageable: unknown;
      userCount: number;
      version: number;
      permissionCodes: string[];
      createTime: string;
      updateTime: string;
    }

    interface TenantListResource {
      id: number;
      tenantCode: string;
      tenantName: string;
      status: string;
      userCount: number;
      version: number;
      createTime: string;
      updateTime: string;
    }

    interface UserListResource {
      id: number;
      userName: string;
      email: string;
      roleCode: string | null;
      roleName: string | null;
      status: string;
      version: number;
      createTime: string;
      updateTime: string;
    }
  }
}
