/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * Generated by `pnpm api:types`.
 *
 * Sources:
 * - ../obsidian-admin-laravel/docs/openapi.yaml
 * - ../obsidian-admin-laravel/docs/api-contract.snapshot
 */
declare namespace BackendContract {
  type EndpointPath =
    | '/audit/list'
    | '/audit/policy'
    | '/audit/policy/history'
    | '/audit/policy/list'
    | '/auth/2fa/disable'
    | '/auth/2fa/enable'
    | '/auth/2fa/setup'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/getUserInfo'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/me'
    | '/auth/menus'
    | '/auth/preferences'
    | '/auth/preferred-locale'
    | '/auth/profile'
    | '/auth/refreshToken'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/timezones'
    | '/auth/verify-email'
    | '/health'
    | '/health/live'
    | '/health/ready'
    | '/language'
    | `/language/${string}`
    | '/language/list'
    | '/language/locales'
    | '/language/messages'
    | '/language/options'
    | '/permission'
    | `/permission/${string}`
    | '/permission/all'
    | '/permission/list'
    | '/role'
    | `/role/${string}`
    | `/role/${string}/permissions`
    | '/role/all'
    | '/role/assignable-permissions'
    | '/role/list'
    | '/system/bootstrap'
    | '/system/feature-flags'
    | '/system/feature-flags/purge'
    | '/system/feature-flags/toggle'
    | `/system/ui/crud-schema/${string}`
    | '/tenant'
    | `/tenant/${string}`
    | '/tenant/all'
    | '/tenant/list'
    | '/theme/config'
    | '/theme/config/reset'
    | '/theme/public-config'
    | '/user'
    | `/user/${string}`
    | `/user/${string}/role`
    | '/user/list';

  interface EndpointMethodMap {
    '/audit/list': 'GET';
    '/audit/policy': 'PUT';
    '/audit/policy/history': 'GET';
    '/audit/policy/list': 'GET';
    '/auth/2fa/disable': 'POST';
    '/auth/2fa/enable': 'POST';
    '/auth/2fa/setup': 'POST';
    '/auth/error': 'GET';
    '/auth/forgot-password': 'POST';
    '/auth/getUserInfo': 'GET';
    '/auth/login': 'POST';
    '/auth/logout': 'POST';
    '/auth/me': 'GET';
    '/auth/menus': 'GET';
    '/auth/preferences': 'PUT';
    '/auth/preferred-locale': 'PUT';
    '/auth/profile': 'GET' | 'PUT';
    '/auth/refreshToken': 'POST';
    '/auth/register': 'POST';
    '/auth/reset-password': 'POST';
    '/auth/timezones': 'GET';
    '/auth/verify-email': 'POST';
    '/health': 'GET';
    '/health/live': 'GET';
    '/health/ready': 'GET';
    '/language': 'POST';
    '/language/{id}': 'DELETE' | 'PUT';
    '/language/list': 'GET';
    '/language/locales': 'GET';
    '/language/messages': 'GET';
    '/language/options': 'GET';
    '/permission': 'POST';
    '/permission/{id}': 'DELETE' | 'PUT';
    '/permission/all': 'GET';
    '/permission/list': 'GET';
    '/role': 'POST';
    '/role/{id}': 'DELETE' | 'PUT';
    '/role/{id}/permissions': 'PUT';
    '/role/all': 'GET';
    '/role/assignable-permissions': 'GET';
    '/role/list': 'GET';
    '/system/bootstrap': 'GET';
    '/system/feature-flags': 'GET';
    '/system/feature-flags/purge': 'DELETE';
    '/system/feature-flags/toggle': 'PUT';
    '/system/ui/crud-schema/{resource}': 'GET';
    '/tenant': 'POST';
    '/tenant/{id}': 'DELETE' | 'PUT';
    '/tenant/all': 'GET';
    '/tenant/list': 'GET';
    '/theme/config': 'GET' | 'PUT';
    '/theme/config/reset': 'POST';
    '/theme/public-config': 'GET';
    '/user': 'POST';
    '/user/{id}': 'DELETE' | 'PUT';
    '/user/{id}/role': 'PUT';
    '/user/list': 'GET';
  }
}

declare namespace OpenAPIContract {
  type SchemaName = 'ApiErrorResponse' | 'ApiResponse';
}
